language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
before_install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
install:
  - "pip install . --use-mirrors"
script: "py.test"
